version = 1
SPDX-PackageName = "z64sim"
SPDX-PackageSupplier = "Alessandro Pellegrini <a.pellegrini@ing.uniroma2.it>"
SPDX-PackageDownloadLocation = "https://github.com/alessandropellegrini/z64sim"

[[annotations]]
path = ["src/main/resources/images/**", "artwork/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2015-2023 Alessandro Pellegrini <a.pellegrini@ing.uniroma2.it>"
SPDX-License-Identifier = "CC-BY-SA-4.0"

[[annotations]]
path = ["AUTHORS", "CODEOWNERS", "README.md", "src/main/resources/**", "src/test/resources/**", "docs/**", "CHANGELOG.md", "docs/**", ".github/ISSUE_TEMPLATE/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2015-2023 Alessandro Pellegrini <a.pellegrini@ing.uniroma2.it>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["pom.xml", "src/main/java/it/uniroma2/pellegrini/z64sim/view/**.form"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2015-2023 Alessandro Pellegrini <a.pellegrini@ing.uniroma2.it>"
SPDX-License-Identifier = "GPL-3.0-only"

[[annotations]]
path = [".DS_Store", "src/.DS_Store", "src/main/.DS_Store"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2015-2023 Alessandro Pellegrini <a.pellegrini@ing.uniroma2.it>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["src/main/java/it/uniroma2/pellegrini/z64sim/assembler/Assembler.java", "src/main/java/it/uniroma2/pellegrini/z64sim/assembler/AssemblerConstants.java", "src/main/java/it/uniroma2/pellegrini/z64sim/assembler/AssemblerTokenManager.java", "src/main/java/it/uniroma2/pellegrini/z64sim/assembler/JavaCharStream.java", "src/main/java/it/uniroma2/pellegrini/z64sim/assembler/ParseException.java", "src/main/java/it/uniroma2/pellegrini/z64sim/assembler/Token.java", "src/main/java/it/uniroma2/pellegrini/z64sim/assembler/TokenMgrError.java"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2015-2023 Alessandro Pellegrini <a.pellegrini@ing.uniroma2.it>"
SPDX-License-Identifier = "GPL-3.0-only"
