/**
 * SPDX-FileCopyrightText: 2015-2022 Alessandro Pellegrini <a.pellegrini@ing.uniroma2.it>
 * SPDX-License-Identifier: GPL-3.0-only
 */
package it.uniroma2.pellegrini.z64sim.view;

import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatLightLaf;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import it.uniroma2.pellegrini.z64sim.PropertyBroker;
import it.uniroma2.pellegrini.z64sim.controller.SettingsController;
import it.uniroma2.pellegrini.z64sim.model.Memory;
import it.uniroma2.pellegrini.z64sim.util.log.Logger;
import it.uniroma2.pellegrini.z64sim.util.log.LoggerFactory;
import it.uniroma2.pellegrini.z64sim.util.queue.Dispatcher;
import it.uniroma2.pellegrini.z64sim.util.queue.Events;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.lang.reflect.Method;
import java.util.Objects;
import java.util.ResourceBundle;

public class MainWindow extends View {
    private static final Logger log = LoggerFactory.getLogger();
    private static MainWindow instance = null;
    private JFrame mainFrame;
    private JPanel mainPanel;
    private JButton button1;
    private JTable memoryView;
    private JTextArea compilerOutput;
    private JEditorPane editor;

    private MainWindow() {
        $$$setupUI$$$();

        this.memoryView.setModel(Memory.getInstance());
        this.compilerOutput.setFont(new Font(Font.MONOSPACED, Font.PLAIN, 12));

        this.mainFrame = new JFrame(PropertyBroker.getPropertyValue("z64sim.name"));
        this.mainFrame.setContentPane(this.mainPanel);
        this.mainFrame.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.mainFrame.setJMenuBar(new MainWindowMenu());
        this.mainFrame.setMinimumSize(new Dimension(Integer.parseInt(PropertyBroker.getPropertyValue("z64sim.ui.minSizeX")), Integer.parseInt(PropertyBroker.getPropertyValue("z64sim.ui.minSizeY"))));
        this.mainFrame.setSize(SettingsController.getWindowSize());
        this.mainFrame.addComponentListener(new ComponentAdapter() {
            public void componentResized(ComponentEvent evt) {
                Component c = (Component) evt.getSource();
                SettingsController.setWindowSize(new Dimension(c.getWidth(), c.getHeight()));
            }
        });
        this.mainFrame.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent windowEvent) {
                Dispatcher.dispatch(Events.QUIT);
            }
        });

        this.setApplicationIcon();
        this.mainFrame.pack();
    }

    public static MainWindow getInstance() {
        if (instance == null)
            instance = new MainWindow();
        return instance;
    }

    public void show() {
        this.mainFrame.setVisible(true);
    }

    private void setApplicationIcon() {
        // Get the icon
        final Image image = new ImageIcon(Objects.requireNonNull(getClass().getResource("/images/frame48.gif"))).getImage();

        // Set the minimized icon for the jar (works out of the box on Windows and Linux)
        this.mainFrame.setIconImage(image);

        // Now the macOS shit to set the icon in the docker. This is the only place that requires us to
        // run on Java >8, otherwise it'd be ugly and nasty to check if com.apple.eawt.Application is accessible.
        try {
            final Taskbar taskbar = Taskbar.getTaskbar();
            taskbar.setIconImage(image);
        } catch (final UnsupportedOperationException ignored) {
        } catch (final SecurityException e) {
            log.error("Security exception while trying to set the icon.");
        }
    }

    @Override
    public boolean dispatch(Events command) {
        switch (command) {
            case SET_THEME_LIGHT:
                this.setTheme(new FlatLightLaf());
                break;
            case SET_THEME_DARK:
                this.setTheme(new FlatDarkLaf());
                break;
        }
        return true;
    }

    private void setTheme(LookAndFeel theme) {
        try {
            UIManager.setLookAndFeel(theme);
            SwingUtilities.updateComponentTreeUI(this.mainFrame);
            this.mainFrame.pack();
        } catch (UnsupportedLookAndFeelException e) {
            e.printStackTrace();
        }
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        Font mainPanelFont = UIManager.getFont("Panel.font");
        if (mainPanelFont != null) mainPanel.setFont(mainPanelFont);
        final JToolBar toolBar1 = new JToolBar();
        Font toolBar1Font = UIManager.getFont("ToolBar.font");
        if (toolBar1Font != null) toolBar1.setFont(toolBar1Font);
        mainPanel.add(toolBar1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(-1, 20), null, 0, false));
        button1 = new JButton();
        Font button1Font = UIManager.getFont("Button.font");
        if (button1Font != null) button1.setFont(button1Font);
        button1.setIcon(new ImageIcon(getClass().getResource("/images/assemble_icon.png")));
        button1.setText("");
        toolBar1.add(button1);
        final JSplitPane splitPane1 = new JSplitPane();
        splitPane1.setDividerSize(5);
        Font splitPane1Font = UIManager.getFont("Panel.font");
        if (splitPane1Font != null) splitPane1.setFont(splitPane1Font);
        splitPane1.setOrientation(0);
        splitPane1.setResizeWeight(0.9);
        mainPanel.add(splitPane1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(200, 200), null, 0, false));
        final JSplitPane splitPane2 = new JSplitPane();
        splitPane2.setDividerSize(5);
        Font splitPane2Font = UIManager.getFont("Panel.font");
        if (splitPane2Font != null) splitPane2.setFont(splitPane2Font);
        splitPane2.setResizeWeight(1.0);
        splitPane1.setLeftComponent(splitPane2);
        final JTabbedPane tabbedPane1 = new JTabbedPane();
        Font tabbedPane1Font = UIManager.getFont("Panel.font");
        if (tabbedPane1Font != null) tabbedPane1.setFont(tabbedPane1Font);
        splitPane2.setLeftComponent(tabbedPane1);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        Font panel1Font = UIManager.getFont("TabbedPane.smallFont");
        if (panel1Font != null) panel1.setFont(panel1Font);
        tabbedPane1.addTab(this.$$$getMessageFromBundle$$$("i18n", "file.tab.untitled"), panel1);
        final JScrollPane scrollPane1 = new JScrollPane();
        Font scrollPane1Font = UIManager.getFont("Panel.font");
        if (scrollPane1Font != null) scrollPane1.setFont(scrollPane1Font);
        panel1.add(scrollPane1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        editor = new JEditorPane();
        Font editorFont = UIManager.getFont("EditorPane.font");
        if (editorFont != null) editor.setFont(editorFont);
        scrollPane1.setViewportView(editor);
        final JScrollPane scrollPane2 = new JScrollPane();
        splitPane2.setRightComponent(scrollPane2);
        memoryView = new JTable();
        memoryView.setFillsViewportHeight(true);
        scrollPane2.setViewportView(memoryView);
        final JScrollPane scrollPane3 = new JScrollPane();
        Font scrollPane3Font = UIManager.getFont("Panel.font");
        if (scrollPane3Font != null) scrollPane3.setFont(scrollPane3Font);
        splitPane1.setRightComponent(scrollPane3);
        compilerOutput = new JTextArea();
        compilerOutput.setEditable(false);
        compilerOutput.setRows(5);
        compilerOutput.setText("a\nb\nc\nd\ne\nf\ng\nh\ni");
        scrollPane3.setViewportView(compilerOutput);
    }

    private static Method $$$cachedGetBundleMethod$$$ = null;

    private String $$$getMessageFromBundle$$$(String path, String key) {
        ResourceBundle bundle;
        try {
            Class<?> thisClass = this.getClass();
            if ($$$cachedGetBundleMethod$$$ == null) {
                Class<?> dynamicBundleClass = thisClass.getClassLoader().loadClass("com.intellij.DynamicBundle");
                $$$cachedGetBundleMethod$$$ = dynamicBundleClass.getMethod("getBundle", String.class, Class.class);
            }
            bundle = (ResourceBundle) $$$cachedGetBundleMethod$$$.invoke(null, path, thisClass);
        } catch (Exception e) {
            bundle = ResourceBundle.getBundle(path);
        }
        return bundle.getString(key);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}
