/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.z64sim.memory.window;

import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;
import org.z64sim.memory.Memory;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//org.z64sim.memory//Memory//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "MemoryTopComponent",
        iconBase = "org/z64sim/memory/window/memory.png",
        persistenceType = TopComponent.PERSISTENCE_ONLY_OPENED
)
@TopComponent.Registration(mode = "properties", openAtStartup = true)
@ActionID(category = "Window", id = "org.z64sim.memory.MemoryTopComponent")
@ActionReference(path = "Menu/Window", position = 3)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_MemoryAction",
        preferredID = "MemoryTopComponent"
)
@Messages({
    "CTL_MemoryAction=Memory",
    "CTL_MemoryTopComponent=Memory View",
    "HINT_MemoryTopComponent=This window allows to explore/modify memory content"
})
public final class MemoryTopComponent extends TopComponent {

    public MemoryTopComponent() {
        initComponents();
        setName(Bundle.CTL_MemoryTopComponent());
        setToolTipText(Bundle.HINT_MemoryTopComponent());
        Memory.setWindow(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();
        memoryTable = new javax.swing.JTable();

        memoryTable.setModel(new MemoryTableModel());
        memoryTable.getTableHeader().setReorderingAllowed(false);
        scrollPane.setViewportView(memoryTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTable memoryTable;
    private javax.swing.JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
}
