# SPDX-FileCopyrightText: 2015-2023 Alessandro Pellegrini <a.pellegrini@ing.uniroma2.it>
# SPDX-License-Identifier: CC0-1.0
name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get release version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build
        run: mvn -B package --file pom.xml
      - name: Prepare files
        run: |
          mv LICENSES/GPL-3.0-only.txt LICENSE.txt
          mv target/z64sim-${{ steps.get_version.outputs.VERSION }}.jar .
      - name: Package
        uses: papeloto/action-zip@v1
        with:
          files: AUTHORS LICENSE.txt README.md z64sim-${{ steps.get_version.outputs.VERSION }}.jar
          dest: z64sim-${{ steps.get_version.outputs.VERSION }}.zip
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: CHANGELOG.md
          files: z64sim-${{ steps.get_version.outputs.VERSION }}.zip
